Asp.Net Core MVC/Controllers/KullaniciController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Layers.Bussines.Abstract;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Layers.Entities.Concrete;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Models.KullaniciVM;
using Microsoft.AspNetCore.Mvc;

namespace JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IKullaniciManager _kullanicimanager;
        private readonly INotyfService _notyf;
        private readonly IMapper _mapper;

        public KullaniciController(IKullaniciManager kullaniciManager, INotyfService notyf, IMapper mapper)
        {
            _kullanicimanager = kullaniciManager;
            _notyf = notyf;
            _mapper = mapper;
        }

        public async Task<IActionResult> UserCreate()
        {
            KullaniciCreateVM kullanici = new();
            return View(kullanici);
        }

        [HttpPost]
        [ValidateAntiForgeryToken] // Token siresi oluşturarak, ilgili formun yabanci tarafindan gonderilip gonderilmedigini kontrol ediyor.
                                   // Formun baska bir kaynak tarafinda gonderilmesi halinde dolandiriciliga karsi alinmis bir onlem.
        public async Task<IActionResult> UserCreate(KullaniciCreateVM kullaniciVm)
        {
            if (ModelState.IsValid) // Validation, ilgili VM'in uygun olup olmamadigini daha ilgili actiona gitmeden kontrol ediyor ve
                                    // uygun olmamasi halinde client tarafina iligli hatayi gonderiyor ve ilgili actiona gitmesini durduruyor
                                    // Fakat tarayicinin JS kullanimi kapatildiginda, VM' in uygun olmamasi halinde hatalari client tarafina
                                    // gondermesiyle birlikte ilgili actiona gitmesini durduramiyor ve haliyle client tarafinda kontrolü ezerek
                                    // server tarafina ulasmis oluyor. Bu sadece ekranda client hatasi gorunse bile verinin bissunes filtresine 
                                    // bissunes filtresine ulasmasi gibi mantiksiz bir olaya yol aciyor. Burada ki if sarti ise bu mantiksizligin
                                    // onune gecmek icin yani; VM uygun olmamasi halinde JS kapali olsa bile bissunes filtresine ulastirmamayi saglar.
            {
                try
                {
                    Kullanici kullanici = new Kullanici()
                    {
                        Ad = kullaniciVm.Ad,
                        City = kullaniciVm.City,
                        Password = kullaniciVm.Password,
                        TcNo = kullaniciVm.TcNo
                    };
                    //_mapper.Map<Kullanici>(kullaniciVm); // Mapper kullanimi

                    await _kullanicimanager.Insert(kullanici);
                    TempData["Basarili Kayit"] = "Kullanıcı Başarıyla Oluşturuldu.";
                    return RedirectToAction("UserCreate");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    _notyf.Error("Hata ! = " + ex.Message);
                    return View(kullaniciVm);
                }
            }
            else
            {
                return View(kullaniciVm);
            }
        }

        public async Task<IActionResult> UserLogin()
        {
            KullaniciLoginVM kullaniciVM = new();
            return View(kullaniciVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UserLogin(KullaniciLoginVM kullaniciLoginVm)
        {
            if (ModelState.IsValid)
            {
                try
                {

                    bool sonuc = await _kullanicimanager.Any(p => p.TcNo == kullaniciLoginVm.TcNo);
                    bool sonuc1 = await _kullanicimanager.Any(p => p.Password == kullaniciLoginVm.Password);

                    if (sonuc1 && sonuc)
                    {
                        return RedirectToAction("Profil");
                    }
                    else
                    {
                        TempData["Basarili Giris"] = "Kullanıcı Girişi Başarılı...";
                        return RedirectToAction("UserLogin");
                    }

                }
                catch (Exception ex)
                {

                    ModelState.AddModelError("", ex.Message);
                    #region Notyf
                    _notyf.Error("Hata! = " + ex.Message);
                    #endregion
                    return View(kullaniciLoginVm);
                }
            }
            else
            {
                return View(kullaniciLoginVm);
            }
        }



        public async Task<IActionResult> Profil()
        {
            return View();
        }

    }
}

Asp.Net Core MVC/Controllers/UrunController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using AutoMapper;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Layers.Bussines.Abstract;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Layers.Entities.Concrete;
using JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Models.UrunVM;
using Microsoft.AspNetCore.Mvc;

namespace JQuery_and_Bootstrap_with_Asp.Net_Core_MVC.Controllers
{
    public class UrunController : Controller
    {
        private readonly IUrunManager _urunManager;
        private readonly IMapper _mapper;
        private readonly INotyfService _notyf;
        public UrunController(IUrunManager urunManager, IMapper mapper, INotyfService notyf)
        {
            _urunManager = urunManager;
            _mapper = mapper;
            _notyf = notyf;
        }
        public async Task<IActionResult> Index()
        {
            IEnumerable<Urun> urunler = await _urunManager.Get();
            return View(urunler);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            _urunManager.DeleteById(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            Urun result = await _urunManager.GetById(id);
            UrunInsertVM result1 = _mapper.Map<UrunInsertVM>(result);
            return View(result1);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdatePost(UrunInsertVM result)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Urun urun = _mapper.Map<Urun>(result);

                    await _urunManager.Update(urun);
                    TempData["Güncelleme Başarılı"] = "Ürün Güncellenmesi Tamamlandı..";
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    _notyf.Error("Hata!: " + ex.Message);
                    return RedirectToAction("Index"); // Tekrar updateye gonderebilmem icin post istegi gondermem gerekiyor.
                }
            }
            else
            {
                ModelState.AddModelError("", "Tarayıcınızın JavaScript kullanımı kapalı olabilir, lütfen kontrol edin.");
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Create()
        {
            UrunInsertVM urunvm = new UrunInsertVM();
            return View(urunvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(UrunInsertVM ınsertVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Urun urun = _mapper.Map<Urun>(ınsertVM);
                    await _urunManager.Insert(urun);
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    _notyf.Error("Hata: " + ex.Message);
                    return View();
                }
            }
            else
            {
                ModelState.AddModelError("", "Tarayıcınızın JavaScript kullanımı engellenmiş olabilir, lütfen kontrol edin.");
                return View();
            }
        }

    }
}

Asp.Net Core MVC/Views/Kullanici/Profil.cshtml
<h1 class="navbar-text mt-3" >Veritabanı İşlemleri</h1>
<div>
    <a asp-controller="Urun" asp-action="Index" class="btn btn-primary mt-1">Urunler</a>
</div>

Asp.Net Core MVC/Views/Kullanici/UserCreate.cshtml
@model KullaniciCreateVM

<div class="container">

    <div class="row">

        <form asp-action="UserCreate" method="post">

            <div class="col-4">

                <div class="form-group">
                    <label asp-for="TcNo" class="form-label">TcNo Giriniz</label>
                    <input asp-for="TcNo" value="" class="form-control" />                   
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="form-label">Password Giriniz</label>
                    <input asp-for="Password" type="password" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Ad" class="form-label">Ad Giriniz</label>
                    <input asp-for="Ad" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="City" class="form-label">Sehir Giriniz</label>
                    <input asp-for="City" class="form-control" />
                </div>
                <div class="form-group mt-2">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>

                <div class="form-group">
                    
                    @{
                        string basarilikayit = TempData["Basarili Kayit"] as string;
                    }
         
                        <div class="text-success">
                            @basarilikayit
                            <div asp-validation-summary="All" class="text-danger"> </div>
                        </div>
                    
                </div>
            </div>

        </form>

    </div>
 
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial"); //Validationun localde jquery linklerinin render edilmesi
    }
    @await Component.InvokeAsync("Notyf") @*Notyf icin js eklentisi*@
                 }

Asp.Net Core MVC/Views/Kullanici/UserLogin.cshtml
@model KullaniciLoginVM

<div class="container">

    <div class="row">

        <form asp-action="UserLogin" method="post">

            <div class="col-4">

                <div class="form-group">
                    <label asp-for="TcNo" class="form-label">TcNo Giriniz</label>
                    <input asp-for="TcNo" value="" class="form-control" />
                </div>
                <div class="form-group">
                    <label asp-for="Password" class="form-label">Password Giriniz</label>
                    <input asp-for="Password" type="password" class="form-control" />
                </div>
                <div class="row" >
                    <div class="form-group mt-2 col-2">
                        <button type="submit" class="btn btn-success">Giriş</button>
                    </div>
                    <div class="form-group mt-2 col-4">
                        <a class="btn btn-primary" asp-action="UserCreate">Üye Ol</a>
                    </div>
                </div>

                <div class="form-group">

                    @{
                        string basarilikayit = TempData["Basarili Giris"] as string;
                    }
                    <div class="text-success">
                        @basarilikayit
                        <div asp-validation-summary="All" class="text-danger"> </div>
                    </div>
                </div>
            </div>

        </form>

    </div>

</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial"); //Validationun localde jquery linklerinin render edilmesi
    }
    @await Component.InvokeAsync("Notyf") @*Notyf icin js eklentisi*@
                 }